### ISSUE TITLE
[Bug] FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。

### ISSUE THREAD

**Issue by q1910182095** [Night-stars-1/Auto_Resonance#30]
### 问题描述

点击1.4exe提示FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。

### 预期行为

1.2版本无异常

### 实际行为

报错无法打开

### 截图或录屏

![Uploading 截图_20240421015149.png…]()
Traceback (most recent call last):
  File "gui.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\view\main_window.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "app\view\running_business_interface.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\api\kmou.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\goods\shop.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\models\config.py", line 21, in <module>
  File "<frozen os>", line 225, in makedirs
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\86135\\Downloads\\Auto_Resonance'

### 程序版本

1.4

### 日志

1.4版本[debug.log](https://github.com/Night-stars-1/Auto_Resonance/files/15049253/debug.log)
1.2版本
[debug.log](https://github.com/Night-stars-1/Auto_Resonance/files/15049254/debug.log)

**Comment by Night-stars-1** [comment]
感谢反馈

**Comment by Night-stars-1** [comment]
已修复
https://github.com/Night-stars-1/Auto_Resonance/releases/tag/v1.0.4.1
