### ISSUE TITLE
Failed to execute script 'gui' due to unhandled exception: Failed to download model: densenet_lite_136-gru-onnx.zip.

### ISSUE THREAD

**Issue by 1139365165** [Night-stars-1/Auto_Resonance#4]
### 问题描述

模型下载失败

### 预期行为

模型下载失败

### 实际行为

模型下载失败

### 截图或录屏

![屏幕截图 2024-04-09 231043](https://github.com/Night-stars-1/Auto_Resonance/assets/66761109/d2e79a2a-b509-43a3-804d-1ebb7e545991)

### 程序版本

1.0

### 日志

Traceback (most recent call last):
  File "cnstd\utils\utils.py", line 249, in get_model_file
  File "cnstd\utils\utils.py", line 178, in download
RuntimeError: Failed downloading url https://sg-models.oss-cn-beijing.aliyuncs.com/cnocr/2.3/densenet_lite_136-gru-onnx.zip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\analysis_tasks.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\presets\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\presets\control.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\exception_handling.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "core\ocr.py", line 15, in <module>
  File "cnocr\cn_ocr.py", line 155, in __init__
  File "cnocr\recognizer.py", line 119, in __init__
  File "cnocr\recognizer.py", line 184, in _assert_and_prepare_model_files
  File "cnstd\utils\utils.py", line 256, in get_model_file
cnstd.utils.utils.ModelDownloadingError: Failed to download model: densenet_lite_136-gru-onnx.zip.
	Please open your VPN and try again. 
	If this error persists, please follow the instruction at [CnSTD/CnOCR Doc](https://www.breezedeus.com/cnocr) to manually download the model files.

**Comment by Night-stars-1** [comment]
这是因为网络环境，导致模型无法下载，下个版本将内置模型

**Comment by Night-stars-1** [comment]
1.0.1应该修了
