### ISSUE TITLE
[Bug] 自动跑商失效

### ISSUE THREAD

**Issue by lowconsume** [Night-stars-1/Auto_Resonance#88]
### 问题描述

单位疲劳只设置了1000，数据源设置为关，自动跑商返回疲劳利润为0，并在不久后出现崩溃信息。关闭火绒web扫描以后状况没有改善。

### 预期行为

不知道，没成功过。
0v0

### 实际行为

崩溃信息:
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)
he above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "requests\adapters.py", line 667, in send

  File "urllib3\connectionpool.py", line 843, in urlopen

  File "urllib3\util\retry.py", line 519, in increment

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='goda.srap.link', port=443): Max retries exceeded with url: /api/fetch/goods_info?uuid= (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

> File "app\common\worker.py", line 27, in run

  File "main.py", line 47, in main

  File "auto\run_business\main.py", line 112, in start

  File "core\api\srap.py", line 41, in get_goods_info

  File "requests\api.py", line 73, in get

  File "requests\api.py", line 59, in request

  File "requests\sessions.py", line 589, in request

  File "requests\sessions.py", line 703, in send

  File "requests\adapters.py", line 698, in send

requests.exceptions.SSLError: HTTPSConnectionPool(host='goda.srap.link', port=443): Max retries exceeded with url: /api/fetch/goods_info?uuid= (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

### 截图或录屏

![image](https://github.com/user-attachments/assets/d8fcc3c9-619e-4744-8f42-2d889f9bb2ea)
![image](https://github.com/user-attachments/assets/067b5d14-981a-4678-80af-5b250da80c96)已在火绒web扫描设置信任

### 程序版本

1.2.7

### 日志

[debug.log](https://github.com/user-attachments/files/18061675/debug.log)

**Comment by Night-stars-1** [comment]
1.3.1已修复
